# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Check build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Volta
      uses: volta-cli/action@v4
    - run: npm ci
    - run: npm run build
    - run: npm test
